// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _windturbine_serviceProxy_h_
#define _windturbine_serviceProxy_h_

#include <staff/client/ServiceClient.h>
#include "windturbine_service.h"

namespace energy
{
namespace WindTurbine
{

//! Proxy for component service energy.WindTurbine.windturbine_service
class windturbine_serviceProxy: public windturbine_service
{
public:
  windturbine_serviceProxy();
  virtual ~windturbine_serviceProxy();
  void Init(const std::string& sServiceUri, const std::string& sSessionId, const std::string& sInstanceId);
  void Deinit();
  virtual staff::ServiceClient* GetClient();
  double windturb_dgcreate();
  int windturb_dginit(double pLine_I_A_Re, double pLine_I_A_Im, double pLine_I_B_Re, double pLine_I_B_Im, double pLine_I_C_Re, double pLine_I_C_Im);
  double windturb_dgsync(double pCircuit_V_A_Re, double pCircuit_V_A_Im, double pCircuit_V_B_Re, double pCircuit_V_B_Im, double pCircuit_V_C_Re, double pCircuit_V_C_Im);
  int windturb_dg_postsync(int t0, int t1);
private:
  mutable staff::ServiceClient m_tClient;
  std::string m_sServiceUri;
};

}
}

namespace staff
{
  class DataObject;
}

#endif

