// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _solarGen_serviceProxy_h_
#define _solarGen_serviceProxy_h_

#include <staff/client/ServiceClient.h>
#include "solarGen_service.h"

namespace energy
{
namespace Solar
{

//! Proxy for component service energy.Solar.solarGen_service
class solarGen_serviceProxy: public solarGen_service
{
public:
  solarGen_serviceProxy();
  virtual ~solarGen_serviceProxy();
  void Init(const std::string& sServiceUri, const std::string& sSessionId, const std::string& sInstanceId);
  void Deinit();
  virtual staff::ServiceClient* GetClient();
  double solarcreate();
  int solarinit(int gen_mode_v, int gen_status_v, int panel_type_v);
  double solarsync(int t0, int t1);
private:
  mutable staff::ServiceClient m_tClient;
  std::string m_sServiceUri;
};

}
}

namespace staff
{
  class DataObject;
}

#endif

